# Fragment와 Ref 동시 사용시 문제점

> This markdown file is for 'scala-script-scope'.
>
> [code](/language/scala-script-scope.ts#96-#101): d:\Samuel\NegahamaOrg.ScalaScript/language/scala-script-scope.ts#96-#101
>
> You can edit this file to add more information about 'Fragment와 Ref 동시 사용시 문제점'

`ScopeProvider`의 `getScope()`는 Linker에서 호출된다.

Langium의 `DocumentBuilder`는 파싱을 하면서 PrecomputedScope로 reference를 수집하는데 명백한 것들은 정확히 설정되지만 설정되지 않는 것들도 있을 수 있다.
이것들이 Link단계에서 `getScope()`을 이용해서 정확하게 설정되는 것으로 보인다. `DefaultScopeProvider`의 동작은 Reference type에 맞게 precomputed 되어진 것들을 검색하고 outer scope까지 확장하면서 심볼을 찾는데 이 과정은 fragment의 사용 여부와 관계없이 정상적으로 잘 처리된다.

문제는 `getScope()`에서 정상적으로 설정되지 않은 `ref`를 참조할때인데 이 경우를 테스트하기 위해서 다음을 준비한다.

```ts
export class MyLanguageScopeProvider extends DefaultScopeProvider {
  override getScope(context: ReferenceInfo): Scope {
    console.log(
      'getScope start,',
      `refText: ${context.reference.$refText}, cstText: ${context.container.$cstNode?.text}`
    )

    const callChain = context.container as ast.CallChain
    const previous = callChain.previous
    if (previous) {
      console.log(
        'getScope previous,',
        `refText: ${previous.element.$refText}, cstText: ${previous.$cstNode?.text}, type: ${previous.$type}, isArray: ${previous.isArray}`
      )
    }
    return super.getScope(context)
  }
}
```

`DefaultScopeProvider`에서 파생된 클래스에서 `getScope()`를 override하고 처음에 위와 같이 로그를 출력하게 하였다.

```ts
CallChain:
  Start ({infer CallChain.previous=current} "." element=[VariableDef:Id]
  // ArrayCallSignature? )*;
  (isArray?='[' ']')? )*;

fragment ArrayCallSignature:
  (isArray?='[' ']');

Start:
  element=[VariableDef:Id]
  // ArrayCallSignature?;
  (isArray?='[' ']')?;
```

위 문법은 `fragment`를 사용하는 경우와 그렇지 않은 경우로 나눠서 테스트할 것이다.

```
val a
val b
a.b
// a[].b
```

위 구문이 테스트되어질 구문인데 `a.b` 인 경우와 `a[].b`인 경우로 나눠서 테스트할 것이다.

즉 총 3가지 경우로 나눠진다. getScope()에서 `ref`를 사용하는 경우, 문법에서 `fragment`를 사용하는 경우, 파싱될 구문에서 `[]`을 사용하는 경우이다.

일단 `ref`를 사용하지 않는 경우는 `fragment`, `[]` 의 사용 여부와는 관계없이 모두 정상적으로 처리된다.

이점이 중요하다.

`a.b` 를 처리할 때

```
getScope start, refText: b, cstText: a.b
getScope previous, refText: a, cstText: a, type: Start, isArray: false
getScope start, refText: a, cstText: a
```

`a[].b` 를 처리할 때

```
getScope start, refText: b, cstText: a[].b
getScope previous, refText: a, cstText: a[], type: Start, isArray: true
getScope start, refText: a, cstText: a[]
```

`getScope()`에서 `ref`를 사용하도록 다음과 같이 변경한다.

```ts
export class MyLanguageScopeProvider extends DefaultScopeProvider {
  override getScope(context: ReferenceInfo): Scope {
    ...
    if (previous) {
      ...
      console.log('ref:', previous.element.ref?.name, previous.element.ref?.$type)
    }
    return super.getScope(context)
  }
}
```

1. fragment 사용 X, [] 사용 X : 정상처리
2. fragment 사용 X, [] 사용 O : 정상처리
3. fragment 사용 O, [] 사용 X : 정상처리
4. fragment 사용 O, [] 사용 O : 비정상처리

ArrayCallSignature를 fragment로 지정하고 []를 사용하면

```
getScope start, refText: b, cstText: a[].b
getScope previous, refText: a, cstText: a[], type: Start, isArray: true
getScope start, refText: a, cstText: undefined
An error occurred while resolving reference to 'a': Error: AST node has no document.
```

와 같이 에러가 발생한다.

이상을 정리하면 `ref`를 사용하지 않거나 `fragment`를 사용하지 않거나 또는 `[]`을 사용하지 않으면 문제가 안되는데 3개를 모두 사용하는 경우에는 문제가 된다는 것이다.

`a[].b`를 파싱할때 `a[]`을 하나로 보고 이것의 `ref`가 precomputedScope단계에서 설정되지 못하는 것으로 보인다.
`ref`가 정상적으로 설정되어지지 않은 상태에서 `ref`를 사용하게 되면 element만 포함된 임시 Reference 개체가 생성되어져 `getScope()`함수를 호출하지만 `getDocument()`에서 에러가 된다. 여기서 `Empty_Scope`를 리턴해도 어짜피 정상적인 동작은 안된다. 어디서 다시 불리는지는 모르겠지만 정상적인 레퍼런스 객체로
두번째 호출되기도 하지만 첫번째 에러로 처리 자체는 안된다.

문제는 프라그먼트인 경우 왜 `a[]`을 `a`로 인식하지 못하는 것일까?

Playground에서 AST를 보면 잠시 나오는데 `isArray`가 element보다 앞에 위치하면서 프라그먼트가 아닌 경우와 달라지는 것을 볼 수 있다.

이 문제는 Langium discussions에서 다뤄지고 있으며
https://github.com/eclipse-langium/langium/discussions/1638

해결책도 제시되었다.
https://github.com/eclipse-langium/langium/pull/1762
